<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align=center><font size = 5>Hands-on Lab: Accessing Your Database with RSQLite</h1>

### Welcome!

In this hands-on lab, you will learn how to connect and discover metadata from database servers with R using RSQLite.

<div class="alert alert-block alert-info" style="margin-top: 20px">
<h3>Tasks</h3>
<ol><ol><ol>
<li><a href="https://#ref6a">Prerequisites</a></li>
<li><a href="https://#ref6b">Create an R notebook</a></li>
<li><a href="https://#ref6c">Load RSQLIte</a></li>
<li><a href="https://#ref6e">Create a database connection</a></li>
<li><a href="https://#ref6f">Connection attributes</a></li>
<li><a href="https://#ref6g">Connection metadata</a></li>
<li><a href="https://#ref6h">Supported data types</a></li>
<li><a href="https://#ref6i">List of tables</a></li>
<li><a href="https://#ref6j">Columns in a table</a></li>
<li><a href="https://#ref6k">Disconnect</a></li>
<li><a href="https://#ref6l">Practice exercises</a></li>
</ol></ol></ol>
<br>
Estimated Time Needed: <strong>15 min</strong>
</div>

<a id="ref6a"></a>

<h3>a. Prerequisites</h3>

In this lab, you will use Jupyter Notebooks within Skills Network (SN) Labs to access data in an SQLite database  using RSQLite.

<a id="ref6b"></a>

<h3>b. Create an R notebook</h3>

Make sure that the notebook kernel has been set to use R (using the dropdown in the top right corner).

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0103EN-SkillsNetwork/labs/Lab%20-%20Accessing%20Your%20Database%20with%20RODBC/kernel.png">

<a id="ref6c"></a>

<h3>c. Load RSQLite</h3>

The RSQlite  package needs to be installed in your notebook. Let’s load the RSQLite package by clicking on the following cell and executing it (Shift+Enter):

In [ ]:
install.packages("RSQLite")

#### Restart Kernel

After installing the RSQLite package, it is necessary to restart R Kernel. Click **Kernel** > **Restart Kernel** from the main menu. This will register the newly installed packages. Now proceed to load the RSQLite package.

In [ ]:
library("RSQLite")

<a id="ref6e"></a>

<h3>b. Create a database connection</h3>

You will use the **dbConnect() method to connect to a database in SQLite Database server**. You need to load the RSQLite driver to the connect method and pass the name of the Database in the dbconnect() method. You can give any database name. If the database does not exist, a database would be created in the SQLite database server with that name.

In [ ]:
con <- dbConnect(RSQLite::SQLite(),"TestDB.sqlite")
con

<a id="ref6f"></a>

<h3>c. Connection attributes</h3>

Let’s examine the connection attributes using the attributes() method and passing the connection object as argument:

In [ ]:
attributes(con)

<a id="ref6g"></a>

<h3>d. Connection metadata</h3>

Now let's review the connection metadata using the `dbGetInfo()` function:

In [ ]:
con.info <- dbGetInfo(conn)

You can print the database version and name using the `db.version` and `dbname` attributes of the connection metadata.

In [ ]:
print(con.info["db.version"])
print(con.info["dbname"])

<a id="ref6h"></a>

<h3>e. Supported data types</h3>

Let’s now examine the data types supported by the database. You will use the **dbDataType() function to display the data types** by passing the driver information and the argument whose datatype needs to be determined.

In [ ]:
dbDataType(RSQLite::SQLite(), 1)
dbDataType(RSQLite::SQLite(), 1L)
dbDataType(RSQLite::SQLite(), "1")
dbDataType(RSQLite::SQLite(), TRUE)
dbDataType(RSQLite::SQLite(), list(raw(1)))

sapply(datasets::quakes, dbDataType, dbObj = RSQLite::SQLite())

<a id="ref6i"></a>

<h3>f. List of tables</h3>

You will use the dbListTables() function to return a list of tabless (i.e. TABLEs, VIEWs, ALIASes, etc.). Initially there will be no tables in the sqlite db which you have created. So, you will use the dbWriteTable() function to create a table in the database by passing the connection object, name of the table and an R dataset name. Here, you will create a **table called 'mtcars' in the dataset mtcars.**

In [ ]:
dbListTables(con)
dbWriteTable(con, "mtcars", mtcars)

You will again use the dbListTables() after creating a table in the database:

In [ ]:
dbListTables(con)

<a id="ref6j"></a>

<h3>g. Columns in a table</h3>

Next, let’s look at column metadata for columns in the table **mtcars**:

In [ ]:
tables1 = dbListTables(con)
for (table in tables1){  
        cat ("\nColumn info for table", table, ":\n")
        col.detail <- dbColumnInfo(dbSendQuery(con,paste( "select * from",table)))
        print(col.detail)
}

<a id="ref6k"></a>

<h3>h. Disconnect</h3>

Finally, as a best practice you should close the database connection once you're done with it.

In [ ]:
dbDisconnect(con)

<a id="ref6l"></a>

### Practise exercises

##### Task 1: Connect to an SQLite database named **MyDB**

In [ ]:
# Write your code here

<details>
<summary>Click here to view/hide hint</summary>
<p>
    
```
Fill in the ...

con <- dbConnect(RSQLite::...,"<Write the name of the SQLite database>")
con
```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
con <- dbConnect(RSQLite::SQLite(),"MyDB.sqlite")
con
```

</details>

##### Task 2: Display the attributes of the connection object

In [ ]:
# Write your code here

<details>
<summary>Click here to view/hide hint</summary>
<p>

```
Fill in the ...
attributes(...)
```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
attributes(con)
```

</details>

##### Task 3: Review the connection metadata using the dbGetInfo() function

In [ ]:
# Write your code here

<details>
<summary>Click here to view/hide hint</summary>

```
Fill in the ...
con.info <- dbGetInfo(...)
print(con.info["<Write the attribute to display database version>"])
print(con.info["<Write the attribute to display database name>"])

```
</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
con.info <- dbGetInfo(con) 
print(con.info["db.version"])
print(con.info["dbname"] )
```

</details>

##### Task 4: Examine the data types supported by the database by checking the data types of the following literals:
##### "yes", 350, FALSE, list(1,2,3)

In [ ]:
# Write your code here

<details>
<summary>Click here to view/hide hint</summary>
<p>

```
Fill in the ...
dbDataType(RSQLite::..., <Write the argument whose datatype has to be determined>)
```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
dbDataType(RSQLite::SQLite(), "yes")
dbDataType(RSQLite::SQLite(), 350)
dbDataType(RSQLite::SQLite(), FALSE)
dbDataType(RSQLite::SQLite(), list(1,2,3))

sapply(datasets::quakes, dbDataType, dbObj = RSQLite::SQLite())
```
</details>

##### Task 5: Create a table named **MyData** in the data set 'iris'

In [ ]:
# Write your code here

<details>
<summary>Click here to view/hide hint</summary>
<p>

```
Fill in the ...
dbWriteTable(con, "<Write the name of the table to be created>", iris)
```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```

dbWriteTable(con, "MyData", iris)

```

</details>

##### Task 6: List the tables in the dataset 'iris'

In [ ]:
# Write your code here

<details>
<summary>Click here to view/hide hint</summary>
<p>

```
Fill in the ...
dbListTables(...)
```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
dbListTables(con)
```

</details>

##### Task 7: Display the column metadata for columns in the table **MyData**

In [ ]:
# Write your code here

<details>
<summary>Click here to view/hide hint</summary>
<p>

```
# Fill in the ...
tables1 = dbListTables(<Write your code here>)
for (table in tables1){  
        cat ("\nColumn info for table", <Write your code here>, ":\n")
        col.detail <- dbColumnInfo(dbSendQuery(<Write your code here>)))
        print(col.detail)

```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
tables1 = dbListTables(con)
for (table in tables1){  
        cat ("\nColumn info for table", table, ":\n")
        col.detail <- dbColumnInfo(dbSendQuery(con,paste( "select * from",table)))
        print(col.detail)
}
```

</details>

##### Task 8: Disconnect from the database

In [ ]:
# Write your code here

<details>
<summary>Click here to view/hide hint</summary>
<p>

```
Fill in the ...
dbDisconnect(...)
```

</details>

<details>
<summary>Click here to view/hide solution</summary>
<p>

```
dbDisconnect(con)
```

</details>

<a id="ref6o"></a>

<h3>Summary</h3>

In this lab you accessed data in a SQlite database using RSQLIte  connection from a R notebook in Jupyter, and discovered different metadata.

<hr>

#### Thank you for completing this lab on getting connected and querying databases using RSQLite.

<hr>

## Authors

*   [Lakshmi Holla](https://www.linkedin.com/in/lakshmi-holla-b39062149/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0103ENSkillsNetwork23619267-2022-01-01)
* [Shreya Khurana](https://www.linkedin.com/in/shreya-khurana-437211237/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0103ENSkillsNetwork896-2023-01-01)

<!--
## Changelog

| Date (YYYY-MM-DD) | Version | Changed By    | Change Description                    |
| ----------------- | ------- | ------------- | ------------------------------------- |
| 2023-08-08   | 1.1     | Shreya Khurana        | Created revised version of the lab|
| 2022-03-08        | 1.0     | Lakshmi Holla | Created Initial Version using RSQLite |
-->
</hr>

<h2 align=center><font size = 5>Copyright &copy; IBM Corporation. All rights reserved.</h2>